---
- name: "Playbook to Create User and  Add Key to EC2 Instance"
  hosts: hosts_to_add_key
  become: true
  tasks:
  
  - name : "Create Groups"
    group:
      name: "{{item}}"
      state: "present"
    with_items:
      - TeamA
      - TeamB

  - name : "Create a user"
    user:
        name: "{{item.name}}" 
        create_home: yes 
        group: "{{item.group}}" 
        state: present 
        ssh_key_file: .ssh/id_rsa 
        ssh_key_type: rsa 
    with_items: 
      - { name: 'user1', group: 'TeamA'}
      - { name: 'user2', group: 'TeamB'}

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{item.name}}"
      state: "{{item.userstate}}"
      key: "{{ lookup('file', '{{ item.key }}')}}"
    with_items:
      - { name: 'user1', key: 'user1.pub', userstate: 'present'}
      - { name: 'user2', key: 'user2.pub', userstate: 'present'}
      

  
